#include "ioport.h"
#include "uart.h"
#include "utils.h"

void uart_setup(){
	out8(UART_LINE_CONTROL_REGISTER, UART_COMMAND_VIEW_COUNTER);
	out8(UART_COUNTER_LOW_PORT, LOW(UART_DEFAULT_COUNTER, 8));
	out8(UART_COUNTER_HIGH_PORT, SPLICE(UART_DEFAULT_COUNTER, 8, 16));
	out8(UART_LINE_CONTROL_REGISTER, UART_COMMAND_VIEW_REG);
	out8(UART_INTERRUPT_ENABLE_REGISTER, UART_INTERRUPT_REG_VALUE);
}

void uart_putchar(char c){
	while(!CHECK_FLAG(in8(UART_STATUS_PORT), UART_FLAG_WRITABLE));
	out8(UART_DATA_REGISTER_PORT, c);
}
