#ifndef UART_H_
#define UART_H_

#define UART_BASE 0x3f8
#define UART_DATA_REGISTER_PORT (UART_BASE + 0)
#define UART_INTERRUPT_ENABLE_REGISTER (UART_BASE + 1)
#define UART_LINE_CONTROL_REGISTER (UART_BASE + 3)
#define UART_STATUS_PORT (UART_BASE + 5)

#define UART_COUNTER_LOW_PORT UART_DATA_REGISTER_PORT
#define UART_COUNTER_HIGH_PORT UART_INTERRUPT_ENABLE_REGISTER

#define UART_DEFAULT_KADR (BIT(0) | BIT(1))
#define UART_STOP_BIT 0
#define UART_EVEN 0

#define UART_DEFAULT_CONFIG ( UART_DEFAULT_KADR | UART_EVEN )

#define UART_COMMAND_VIEW_COUNTER (BIT(7) | UART_DEFAULT_CONFIG)
#define UART_COMMAND_VIEW_REG UART_DEFAULT_CONFIG

#define UART_DEFAULT_COUNTER 10000
#define UART_INTERRUPT_REG_VALUE 0

#define UART_FLAG_WRITABLE BIT(5)

void uart_setup();
void uart_putchar(char c);



#endif /* UART_H_ */
